// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCYlba5LPLMPsi8nzVA9tXWrEhBUtjA28',
    appId: '1:36219395872:web:1ef46562bb98abadbc8145',
    messagingSenderId: '36219395872',
    projectId: 'dance-fever-a5f33',
    authDomain: 'dance-fever-a5f33.firebaseapp.com',
    storageBucket: 'dance-fever-a5f33.firebasestorage.app',
    measurementId: 'G-HJNHWYDPZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtpN20f3BcCIYNaOEJPFHdNHs9h5xQR9o',
    appId: '1:36219395872:android:31d01428df8c1cffbc8145',
    messagingSenderId: '36219395872',
    projectId: 'dance-fever-a5f33',
    storageBucket: 'dance-fever-a5f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBg7WTwNIKcOgJLXUgXnMtYrgM8I-LJThM',
    appId: '1:36219395872:ios:6255848ef1206350bc8145',
    messagingSenderId: '36219395872',
    projectId: 'dance-fever-a5f33',
    storageBucket: 'dance-fever-a5f33.firebasestorage.app',
    iosBundleId: 'com.example.danceFever',
  );
}
